CREATE DATABASE DISCIPULOS_DE_EVANDRO;
USE DISCIPULOS_DE_EVANDRO;
CREATE TABLE ALUNOS (
    ALUNO_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TURMA VARCHAR(50),
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR(100),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE LIVROS (
	LIVRO_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(200) NOT NULL,
    AUTOR VARCHAR(100)  NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE EMPRÉSTIMOS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ALUNO_ID INT NOT NULL,
    LIVRO_ID INT NOT NULL,
    DATA_EMPRESTIMO DATE NOT NULL,
    DATA_PREVISAO_DEVOLUCAO DATE NOT NULL,
    DATA_DEVOLUCAO DATE,
    STATUS ENUM('ATIVO', 'DEVOLVIDO', 'ATRASADO') DEFAULT 'ATIVO',
    OBSERVACAO TEXT,
    FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID) ON DELETE CASCADE,
    FOREIGN KEY (LIVRO_ID) REFERENCES LIVROS(LIVRO_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;